QUERYLMS_VERSION = "0.2.5.0"
LMS_HOST = "127.0.0.1"
LMS_PORT = "9000"
LMS_BRDCST_MSG = b'eJSON\0'
LMS_BRDCST_PORT = 3483
LMS_BRDCST_TIMEOUT = 5
LMS_QUERY_BASE_URL = 'http://{}:{}/'
LMS_QUERY_ENDPOINT = '{}jsonrpc.js'
